# These are supported funding model platforms

github: Adel-Ayoub
# ko_fi: Adel-Ayoub
# liberapay: Adel-Ayoub
# open_collective: Adel-Ayoub
# patreon: Adel-Ayoub
# tidelift: Adel-Ayoub
# community_bridge: Adel-Ayoub
# issuehunt: Adel-Ayoub
# otechie: Adel-Ayoub
# custom: https://github.com/Adel-Ayoub/cshell
